# Generated by Django 5.0.4 on 2024-04-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0002_banner_alter_endereco_rua_alter_produto_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=200, null=True)),
                ("codigo_hex", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="cor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="loja.cor",
            ),
        ),
    ]
