# Generated by Django 5.0.4 on 2024-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0003_cor_alter_categoria_options_alter_itemestoque_cor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cor",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="tipo",
            options={"ordering": ["nome"]},
        ),
        migrations.AddField(
            model_name="categoria",
            name="slug",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tipo",
            name="slug",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
