# Generated by Django 5.0.4 on 2024-04-19 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loja", "0005_pagamento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagamento",
            old_name="id_pedido",
            new_name="id_pagamento",
        ),
    ]
